config/routes.rb
Friendbc::Application.routes.draw do
  get '/auth/facebook/callback' => 'auth#facebook', as: 'facebook_callback'
  get '/auth/twitter/callback' => 'auth#twitter'

  resources :comments

  resources :posts

  root 'users#index'

  get '/session/new', controller: 'sessions', action: 'new', as: 'new_session'
  post '/session', controller: 'sessions', action: 'create', as: 'session'
  delete '/session', controller: 'sessions', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/user.rb
require 'open-uri'

class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true, uniqueness: true

  has_many :posts, dependent: :destroy

  def poll_twitter
    client = Twitter::REST::Client.new do |config|
      config.consumer_key = ENV["FRIENDBC_TWITTER_CONSUMER_KEY"]
      config.consumer_secret = ENV["FRIENDBC_TWITTER_CONSUMER_SECRET"]
      config.access_token = self.twitter_access_token
      config.access_token_secret = self.twitter_access_token_secret
    end

    return client.home_timeline(count: 200)
  end

  def poll_facebook
    begin
      url = "https://graph.facebook.com/me/home?access_token=#{self.facebook_access_token}&limit=200"
      raw_response = open(url).read
      parsed_response = JSON.parse(raw_response)
      posts = parsed_response['data'].select { |p| p['type'] == 'video' }
    rescue Exception => e
      puts e
      posts = []
    end

    posts.each do |the_post|
      post = Post.new
      post.sharer_name = the_post['from']['name']
      post.sharer_facebook_id = the_post['from']['id']
      post.message = the_post['message']
      post.link = the_post['link']
      post.created_time = the_post['created_time']
      post.post_facebook_id = the_post['id']
      post.user_id = self.id
      unless post.save
        post = Post.find_by(post_facebook_id: the_post['id'])
      end
      if the_post['comments'].present?
        the_post['comments']['data'].each do |the_comment|
          comment = Comment.new
          comment.commenter_name = the_comment['from']['name']
          comment.commenter_facebook_id = the_comment['from']['id']
          comment.message = the_comment['message']
          comment.created_time = the_comment['created_time']
          comment.comment_facebook_id = the_comment['id']
          comment.post_id = post.id
          comment.save
        end
      end
    end
    puts "Successfully polled for #{self.username}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :current_user_must_be_user, only: [:show, :edit, :update, :destroy]

  def current_user_must_be_user
    unless current_user == @user
      redirect_to :back, notice: 'You are not authorized for that.'
    end
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @posts = @user.posts
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :first_name, :last_name, :facebook_access_token, :facebook_id)
    end
end

app/views/users/_comment.html.erb
<div class="media">
  <div class="pull-left">
    <%= image_tag "https://graph.facebook.com/#{comment.commenter_facebook_id}/picture", class: 'media-object' %>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= comment.commenter_name %>
      <small><%= time_ago_in_words(comment.created_time) %> ago</small>
    </h4>
    <p><%= comment.message %></p>
  </div>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |message| %>
    <div><%= message %></div>
  <% end %>
<% end %>

<%= form_for @user do |f| %>


  <div>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>

  <div>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_post.html.erb
<li class="media">
  <div class="pull-left">
    <%= image_tag "https://graph.facebook.com/#{post.sharer_facebook_id}/picture", class: 'media-object' %>
  </div>
  <div class="media-body">
    <h2 class="media-heading">
      <%= post.sharer_name %>
      <small><%= time_ago_in_words(post.created_time) %> ago</small>
    </h2>
    <p class="lead"><%= post.message %></p>
    <%= display_video(post.link) %>
    <% if post.comments.any? %>
      <% post.comments.each do |the_comment| %>
        <%= render 'comment', comment: the_comment %>
      <% end %>
    <% end %>
  </div>
  <hr>
</li>

app/views/users/edit.html.erb
<h1>Editing <%= @user.username %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Sign Up', new_user_url, class: 'btn btn-success' %></p>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th>First name</th>
      <th>Last name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.username, user %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_user_url(user) %></td>
      <td><%= link_to '<i class="icon-trash"></i>'.html_safe, user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <h1>
    <%= @user.username %>
    <small>
      <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_user_url(@user) %>
      <%= link_to '<i class="icon-trash"></i>'.html_safe, @user, method: 'delete', data: { confirm: "Do you really want to delete this user?" } %>
      <%= link_to '<i class="icon-facebook"></i>'.html_safe, "https://www.facebook.com/dialog/oauth?client_id=#{ENV["FRIENDBC_FACEBOOK_APP_ID"]}&redirect_uri=#{facebook_callback_url}&scope=read_stream" %>
      <%= link_to '<i class="icon-twitter"></i>'.html_safe, "/auth/twitter" %>
    </small>
  </h1>
</div>

<ul class="media-list">
  <% @posts.each do |the_post| %>
    <%= render 'post', post: the_post %>
  <% end %>
</ul>