config/routes.rb
Friendbc::Application.routes.draw do
  get '/auth/facebook/callback' => 'auth#facebook', as: 'facebook_callback'
  get '/auth/twitter/callback' => 'auth#twitter'

  resources :comments

  resources :posts

  root 'users#index'

  get '/session/new', controller: 'sessions', action: 'new', as: 'new_session'
  post '/session', controller: 'sessions', action: 'create', as: 'session'
  delete '/session', controller: 'sessions', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Friendbc</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>


  <link href="//netdna.bootstrapcdn.com/bootswatch/2.3.2/spacelab/bootstrap.min.css" rel="stylesheet">

  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to image_tag('logo.png'), root_url, class: 'brand' %>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Users", users_url %></li>
            <% if current_user.present? %>
              <li><%= link_to current_user.username, current_user  %></li>
              <li><%= link_to 'Sign Out', session_url, method: 'delete' %></li>
            <% else %>
              <li><%= link_to 'Sign In', new_session_url %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container">

    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">&times;</a>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>